In [1]:
# input library
import warnings
warnings.filterwarnings("ignore") # unnecessary item not show
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("weight-height.csv") # csv file input

In [3]:
df.head() # csv file show

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.shape # columns and row size

(8555, 3)

In [5]:
df.info() # csv file all information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   object 
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), object(1)
memory usage: 200.6+ KB


In [6]:
df.describe() #csv file all details

Height       Weight
count  8555.000000  8555.000000
mean     66.809925   165.632735
std       3.851454    32.043922
min      54.616858    65.780000
25%      63.957684   139.876803
50%      66.985923   168.521567
75%      69.604427   190.666305
max      80.450000   269.989698

# Encoder

In [7]:
from sklearn.preprocessing import LabelEncoder # input LabelEncoder

In [8]:
le = LabelEncoder() # createing LabelEncoder object

In [9]:
from pandas.core.dtypes.common import is_numeric_dtype # input numeric data type 

In [10]:
# useing  for loop to Encoder
for column in df.columns: 
    if is_numeric_dtype(df[column]):
        continue
    else:
        df[column] = le.fit_transform(df[column])

In [11]:
df.head() # LabelEncoder csv file show

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [12]:
df.to_csv("data.csv") # csv file download

In [13]:
x = df[["Gender","Height"]] # two dimensional array to x (Gender & Height)

In [14]:
y = df[["Weight"]] # two dimensional array to y (Weight)

In [15]:
x.head() # two dimensional array to x show

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [16]:
y.head() # two dimensional array to y show

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [17]:
from sklearn.model_selection import train_test_split # input train_test_split 

In [18]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=.70,random_state=1) #training & testing  data

In [19]:
xtrain.head() # training x data show

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [20]:
xtrain.shape # training x data size

(5988, 2)

In [21]:
ytrain.head() # training y data show

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [22]:
ytrain.shape # training y data size

(5988, 1)

In [23]:
xtest.head() # testing x data show

Gender     Height
7154       0  65.068038
3258       1  70.824643
2188       1  68.663594
5609       0  65.987610
3186       1  70.901461

In [24]:
xtest.shape # testing x data size

(2567, 2)

In [25]:
ytest.head() # testing y data show

Weight
7154  160.800726
3258  184.516688
2188  184.262796
5609  166.844114
3186  200.466282

In [26]:
ytest.shape # testing y data size

(2567, 1)

# Linear Regression

In [27]:
from sklearn.linear_model import LinearRegression # input LinearRegression

In [28]:
reg = LinearRegression() # createing LinearRegression object

In [29]:
reg.fit(xtrain,ytrain) #training and testing data the model

LinearRegression()

In [30]:
reg.coef_ # m

array([[19.34359322,  5.96887438]])

In [31]:
reg.intercept_ # c

array([-244.55280903])

In [32]:
reg.predict(xtest) # all number prediction

array([[143.83013436],
       [197.53417989],
       [184.63515112],
       ...,
       [160.7078525 ],
       [186.82852694],
       [201.4226542 ]])

# Accuracy

In [33]:
reg.score(xtrain,ytrain) # training accuracy

0.8972135459668117

In [34]:
reg.score(xtest,ytest) # testing accuracy

0.9059959607091161

# MSE

In [35]:
from sklearn.metrics import mean_squared_error # input mean_squared_error

In [36]:
mean_squared_error(ytest,reg.predict(xtest)) # actual - predicted

99.67250998070031

# KNeighborsRegressor

In [37]:
from sklearn.neighbors import KNeighborsRegressor # input KNeighborsRegressor

In [38]:
knr = KNeighborsRegressor # createing KNeighborsRegressor object

# KNN(distance)

In [39]:
n = knr(n_neighbors=15) # createing distance

In [40]:
n.fit(xtrain,ytrain) # training and testing data the model

KNeighborsRegressor(n_neighbors=15)

In [41]:
n.predict(xtest) # all number prediction

array([[147.52628523],
       [199.18926683],
       [182.00210297],
       ...,
       [162.47572602],
       [185.50562864],
       [200.64847604]])

# Accuracy

In [42]:
n.score(xtrain,ytrain) # training accuracy

0.9030768628511936

In [43]:
n.score(xtest,ytest) # test accuracy

0.8981209832950068

# MSE

In [44]:
mean_squared_error(ytest,n.predict(xtest)) # actual - predicted

108.0223508048458

# KNN(uniform)

In [45]:
n_1= knr(weights='uniform') # createing uniform

In [46]:
n_1.fit(xtrain,ytrain) # training and testing data the model

KNeighborsRegressor()

In [47]:
n_1.predict(xtest) # all number prediction

array([[150.1761117 ],
       [197.46276978],
       [179.03501546],
       ...,
       [160.26227546],
       [180.65461322],
       [200.56451578]])

# Accuracy

In [48]:
n_1.score(xtrain,ytrain) # training accuracy

0.9170756955071054

In [49]:
n_1.score(xtest,ytest) # test accuracy

0.8838502073708883

# MSE

In [50]:
mean_squared_error(ytest,n_1.predict(xtest)) # actual - predicted

123.15365863436983

# KNeighborsClassifier

In [51]:
df.head() # csv file show

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [52]:
x = df[["Height","Weight"]] # two dimensional array to x (Gender & Height)

In [53]:
y = df[["Gender"]] # two dimensional array to y (Weight)

In [54]:
x.head()  # two dimensional array to y show

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [55]:
y.head() # two dimensional array to x show

Gender
0       1
1       1
2       1
3       1
4       1

In [56]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.70,random_state=1) #training & testing  data

In [57]:
xtrain.head() # training x data show

Height      Weight
1277  72.385301  189.165592
5361  60.960147  124.876796
5728  69.119292  168.864403
4276  68.271050  172.941248
3112  64.991405  144.551044

In [58]:
xtrain.shape # training x data size

(5988, 2)

In [59]:
ytrain.head() # training y data show

Gender
1277       1
5361       0
5728       0
4276       1
3112       1

In [60]:
ytrain.shape # training y data size

(5988, 1)

In [61]:
from sklearn.neighbors import KNeighborsClassifier # input KNeighborsClassifier

In [62]:
knc = KNeighborsClassifier # createing KNeighborsClassifier object

# KNN(distance)

In [63]:
n_2 = knc(n_neighbors=15) # createing distance

In [64]:
n_2.fit(xtrain,ytrain) # training and testing data the model

KNeighborsClassifier(n_neighbors=15)

In [65]:
n_2.predict(xtest) # all number prediction

array([1, 1, 1, ..., 0, 1, 1])

# Accuracy

In [66]:
n_2.score(xtrain,ytrain) # training accuracy

0.9186706746826987

In [67]:
n_2.score(xtest,ytest) # testing accuracy

0.9244253992987924

# MSE

In [68]:
mean_squared_error(ytest,n_2.predict(xtest)) # actual - predicted

0.07557460070120764

# KNN(uniform)

In [69]:
n_3 = knc(weights='uniform') # createing uniform

In [70]:
n_3.fit(xtrain,ytrain) # training and testing data the model

KNeighborsClassifier()

In [71]:
n_3.predict(xtest) # all number prediction

array([1, 1, 1, ..., 0, 1, 1])

# Accuracy

In [72]:
n_3.score(xtrain,ytrain) # training accuracy

0.9263527054108216

In [73]:
n_3.score(xtest,ytest) # testing accuracy

0.9146864043630697